<?php

namespace App\Filament\Pages;

use App\Enums\Icon\Ionicons;
use App\Filament\Widgets\DashboardChartCategoryExpense;
use App\Filament\Widgets\DashboardChartCategoryIncome;
use App\Filament\Widgets\DashboardChartInvoice;
use App\Filament\Widgets\DashboardStatsOverview;
use App\Filament\Widgets\DashboardWidgetDailyPerSource;
use Carbon\Carbon;
use Coolsam\Flatpickr\Enums\FlatpickrPosition;
use Coolsam\Flatpickr\Forms\Components\Flatpickr;
use Filafly\Icons\Iconoir\Enums\Iconoir;
use Filament\Pages\Dashboard as BaseDashboard;
use Filament\Pages\Dashboard\Concerns\HasFiltersForm;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Malzariey\FilamentDaterangepickerFilter\Fields\DateRangePicker;

class Dashboard extends BaseDashboard
{
    use HasFiltersForm;

    protected static string|null|\BackedEnum $navigationIcon = Iconoir::DashboardSpeed;
    //    protected string $view = 'filament.pages.dashboard';

    protected ?string $subheading = "Visão geral das suas finanças";

    public function getColumns(): int|array
    {
        return [
            'sm' => 12,
            'md' => 12,
            'xl' => 12,
        ]; // TODO: Change the autogenerated stub
    }

    public function filtersForm(Schema $schema): Schema
    {
        return $schema
            ->schema([
                Grid::make([
                    'default' => 12,
                ])
                    ->schema([
                        Flatpickr::make('due_date')
                            ->hiddenLabel()
                            ->displayFormat('F / Y')
                            ->defaultDate(Carbon::now()->startOfMonth())
                            ->locale('pt')
                            ->format('Y-m')
                            ->monthPicker()
                            ->position(FlatpickrPosition::AUTO_CENTER)
                            ->default(Carbon::now()->startOfMonth()->format('Y-m'))
                            // Ocupa 4 colunas e pula as 4 primeiras (ficando no centro: 4 + 4 + 4 = 12)
                            ->columnStart(5)
                            ->columnSpan(3)
                    ])
                ->columnSpanFull(),
            ]);
    }

    public function getWidgets(): array
    {
        return [
            DashboardStatsOverview::class,
            DashboardWidgetDailyPerSource::class,
            DashboardChartCategoryIncome::class,
            DashboardChartCategoryExpense::class,
            DashboardChartInvoice::class
        ];
    }
}
